import type { FaqAnswer } from './answers';

type AiEraFaqInput = Omit<
  FaqAnswer,
  'answer' | 'cacheMode' | 'answerSource' | 'skippedGroq' | 'visibility'
> & {
  visibility?: FaqAnswer['visibility'];
};

const sharedAiEraGuardrailsKo = [
  'Не утверждать категорично, что ИИ никогда не заменит людей.',
  'Не утверждать, что ИИ может полностью заменить целую команду разработчиков.',
  'Не описывать использование ИИ как замену реальным инженерным навыкам.',
  'Подтверждать аргументы фактами, такими как разработка Ask Romeo, опыт тестирования в Sminex App, Elme Messer, DPD и работа с RAG.',
];

const sharedAiEraGuardrailsEn = [
  'Do not claim AI can never replace humans.',
  'Do not imply Oosu can replace an entire team with AI.',
  'Do not frame AI usage as a substitute for skill.',
  'Tie claims back to evidence such as AskOosu, OOSU SALON, GfK, team projects, or RAG operations.',
];

export const AI_ERA_COMPETITIVENESS_FAQ_ANSWERS: FaqAnswer[] = [
  createAiEraAnswer({
    id: 'faq.ai_era.replace_developer.default',
    legacyIds: ['faq.ai_competitiveness.irreplaceable_work.default'],
    intentId: 'ai_era.replace_developer',
    entityId: 'ai_era_competitiveness',
    language: 'ru',
    quickLabel: 'ИИ и разработчики',
    displayQuestion:
      'Заменит ли ИИ разработчиков? Что думает об этом Роман?',
    alternativeDisplayQuestions: [
      'Что вы умеете делать такого, что ИИ не сможет заменить?',
      'Если ИИ может писать код, зачем нанимать младших специалистов?',
    ],
    patterns: [
      'ИИ заменит разработчиков',
      'устаревание профессии разработчика',
      'разработчики в эпоху ИИ',
      'востребованность программистов',
      'зачем нанимать разработчиков если есть ИИ',
      'что ИИ не может заменить',
      'ИИ пишет весь код',
    ],
    shortAnswer:
      'ИИ не может заменить не сам процесс написания кода, а способность анализировать и проверять сгенерированные результаты в контексте реальных потребностей пользователей и бизнес-логики.',
    defaultAnswer: [
      'Я считаю, что ИИ действительно ускоряет написание кода. Однако принятие решений о том, что именно разрабатывать и можно ли доверять результату работы нейросети — это по-прежнему задача человека.',
      '',
      'Результаты работы ИИ могут быть быстрыми, но их необходимо сопоставлять со сценариями реальных пользователей, архитектурой проекта и требованиями к качеству. В Ask Romeo ИИ мог предлагать разные варианты реализации, но финальные решения — такие как разделение RAG и FAQ Cache или использование PostgreSQL с pgvector для векторного кэша — принимал и проверял я сам.',
      '',
      '> ИИ дает скорость выполнения. Но определение направления, продуктовое чутье и критический контроль качества остаются за инженером. Именно в этом направлении я развиваюсь.',
      '',
      'Поэтому более реалистичный вопрос звучит не «заменит ли ИИ разработчиков?», а «заменят ли разработчики, умеющие эффективно использовать ИИ, тех, кто этого не умеет?»',
    ].join('\n'),
    detailedAnswer: [
      'Я не хочу сводить это к какому-то загадочному человеческому превосходству. Более точная формулировка заключается в том, что ИИ силен, но полностью оторван от контекста реального мира.',
      '',
      'Языковая модель похожа на человека, изолированного на необитаемом острове с огромными стопками книг. У нее много знаний и высокая скорость, но она не знает напрямую, в какой именно момент пользователь испытывает трудности, что нужно команде на этой неделе или какая формулировка интерфейса разрушит доверие к сервису.',
      '',
      'Тестирование таких экосистем, как Sminex App, и развитие Ask Romeo приучили меня смотреть на продукт глазами пользователей и отслеживать корректность интеграции систем. Это и есть тот стандарт, который я использую при проверке и доработке сгенерированного ИИ кода.',
      '',
      'Поэтому задача Романа — не конкурировать с ИИ, а интегрировать возможности ИИ в реальный продуктовый контекст и нести ответственность за качество результата.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.replace_developer.default',
      'ops.ai-agent-workflow.ko',
      'ops.product-build-loop.ko',
      'ops.code-review-with-ai.ko',
      'decision.why-not-overclaim-ai-era.ko',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsKo,
    matchedEntityIds: [
      'ai_era_competitiveness',
      'ai_usage',
      'profile',
      'askoosu',
    ],
    confidence: 0.92,
  }),
  createAiEraAnswer({
    id: 'faq.ai_era.skill_atrophy.default',
    intentId: 'ai_era.skill_atrophy',
    entityId: 'ai_era_competitiveness',
    language: 'ru',
    quickLabel: 'ИИ и навыки',
    displayQuestion: 'Не приведет ли частое использование ИИ к деградации собственных инженерных навыков?',
    alternativeDisplayQuestions: [
      'Вы действительно понимаете код, который генерирует ИИ, и можете написать его сами?',
      'Сможете ли вы программировать и тестировать без ИИ?',
    ],
    patterns: [
      'деградация навыков из-за ИИ',
      'реальные навыки разработки',
      'код без ИИ',
      'ИИ-грамотность и навыки',
      'слишком частое использование ИИ',
      'умеет ли Роман писать код сам',
    ],
    shortAnswer:
      'Использовать ИИ эффективно — не значит слепо доверять ему. Роман сначала проектирует архитектуру и логику работы системы, а затем использует ИИ для ускорения написания рутинного кода, тщательно проверяя результат.',
    defaultAnswer: [
      'На ранних этапах я сталкивался с этим риском: сгенерированный ИИ код работал, но когда я не понимал, почему именно он работает, я не мог исправить его при сбое. Этот опыт сформировал мой текущий подход к работе.',
      '',
      'Теперь я сначала четко определяю цель, рамки изменений, ограничения и критерии тестирования перед тем, как обратиться к ИИ. Получив результат, я проверяю, соответствует ли код реальной структуре файлов, совпадают ли поля API и UI, не допущены ли уязвимости и не утекли ли конфиденциальные данные.',
      '',
      '> Чтобы эффективно использовать ИИ, необходимо уметь проводить качественный аудит и ревью его результатов.',
      '',
      'А для проведения такого аудита требуются глубокие собственные знания. Поэтому ИИ — это не замена пониманию, а инструмент, ускоряющий обучение и выполнение рутины.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.skill_atrophy.default',
      'ops.code-review-with-ai.ko',
      'postmortem.instagram-clone-fullstack-lessons.ko',
      'decision.why-not-overclaim-ai-era.ko',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsKo,
    matchedEntityIds: ['ai_era_competitiveness', 'ai_usage', 'profile'],
    confidence: 0.91,
  }),
  createAiEraAnswer({
    id: 'faq.ai_era.competitiveness_source.default',
    legacyIds: ['faq.ai_competitiveness.real_competitor.default'],
    intentId: 'ai_era.competitiveness_source',
    entityId: 'ai_era_competitiveness',
    language: 'ru',
    quickLabel: 'Преимущество',
    displayQuestion: 'В чем конкурентное преимущество Романа в эпоху развития ИИ?',
    alternativeDisplayQuestions: [
      'Кого вы считаете своими конкурентами?',
      'Почему стоит нанять Романа в эпоху ИИ?',
    ],
    patterns: [
      'конкурентное преимущество',
      'сильные стороны',
      'отличия в эпоху ИИ',
      'почему стоит нанять Романа',
      'что отличает Романа',
      'конкуренция с ИИ',
      'сравнение с ИИ',
    ],
    shortAnswer:
      'Преимущество Романа заключается не в соревновании с ИИ, а в умении соединять возможности ИИ с реальными бизнес-задачами, качеством продукта и строгим процессом верификации.',
    defaultAnswer: [
      'Я считаю, что мое преимущество складывается из трех факторов:',
      '',
      '**1. Связанный опыт.** Понимание бизнес-логики, тестирование сложных интеграций (Web, Mobile, API, микросервисы) в коммерческих проектах вроде Sminex, а также разработка собственного портфолио Ask Romeo на Next.js с RAG-поиском — все эти этапы дополняют друг друга.',
      '',
      '**2. Умение соединять ИИ с реальностью.** ИИ предлагает варианты решений, но оценивать, насколько они подходят конкретному продукту, пользователям и инфраструктуре команды, должен инженер на основе своего опыта.',
      '',
      '**3. Скорость экспериментов и интеграции.** Инструменты вроде Vercel AI SDK, векторного поиска pgvector, Cloudflare Tunnel — это не просто статьи в документации, которые я читал. Я применил их на практике при создании Ask Romeo и успешно развернул проект.',
      '',
      '> Сам по себе ИИ — не конкурент. Мои конкуренты — это инженеры, которые используют ИИ эффективнее других. И я делаю все, чтобы быть в их числе.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.competitiveness_source.default',
      'decision.why-ai-native-working-thesis.ko',
      'project.askoosu.fact',
      'profile.learning_style',
      'career.timeline',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsKo,
    matchedEntityIds: [
      'ai_era_competitiveness',
      'profile',
      'career',
      'askoosu',
    ],
    confidence: 0.92,
  }),
  createAiEraAnswer({
    id: 'faq.ai_competitiveness.ai_fluency_vs_dependency.default',
    intentId: 'ai_competitiveness.ai_fluency_vs_dependency',
    entityId: 'ai_era_competitiveness',
    language: 'ru',
    quickLabel: 'ИИ-грамотность',
    displayQuestion: 'В чем разница между умелым использованием ИИ (AI fluency) и зависимостью от него (AI dependency)?',
    patterns: [
      'зависимость от ИИ',
      'умелое использование ИИ',
      'код без нейросетей',
      'ИИ грамотность',
      'разница между fluency и dependency',
    ],
    shortAnswer:
      'Зависимость от ИИ — это копирование предложенного кода без понимания принципов его работы. ИИ-грамотность — это определение целей и критериев проверки кода, при котором ответственность за интеграцию полностью лежит на разработчике.',
    defaultAnswer: [
      'Быть зависимым от ИИ — значит слепо внедрять результаты генерации, не понимая, как устроен код под капотом. Уметь использовать ИИ — значит сначала спроектировать архитектуру, задать ограничения и критерии валидации, а затем критически оценить и интегрировать предложенное решение.',
      '',
      'При работе с ИИ я всегда формулирую цель, область изменений, ограничения и тест-кейсы до генерации, а затем провожу обязательное ревью полученного кода в контексте всей кодовой базы продукта.',
      '',
      '> Код от ИИ — это лишь черновик. Ответственность за то, что попадет на прод, всегда несет инженер.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_competitiveness.ai_fluency_vs_dependency.default',
      'ops.ai-agent-workflow.ko',
      'ops.code-review-with-ai.ko',
      'ops.answer-quality-loop.ko',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsKo,
    matchedEntityIds: ['ai_era_competitiveness', 'ai_usage', 'askoosu'],
    confidence: 0.91,
  }),
  createAiEraAnswer({
    id: 'faq.ai_era.replace_developer.default',
    legacyIds: ['faq.ai_competitiveness.irreplaceable_work.default'],
    intentId: 'ai_era.replace_developer',
    entityId: 'ai_era_competitiveness',
    language: 'en',
    quickLabel: 'AI-era edge',
    displayQuestion: 'Will AI replace developers? What does Oosu think?',
    alternativeDisplayQuestions: [
      "What can you do that AI can't replace?",
      'If AI writes code, why hire a junior developer?',
    ],
    patterns: [
      'AI replace developer',
      'developers becoming obsolete',
      'AI era developer',
      'developer job security',
      'why hire developers when AI exists',
      "what can you do that AI can't replace",
      'AI writes all the code',
    ],
    shortAnswer:
      "What AI can't replace is not simply typing code. It is judging and refining AI output against real user problems, product context, UX flow, and trust standards.",
    defaultAnswer: [
      'I think AI genuinely accelerates execution. But deciding what to execute, and whether the result is trustworthy enough for a product, is still human work.',
      '',
      'AI output can be fast, but it still has to be checked against real user problems, product context, UX flow, and trust standards. In AskOosu, AI could propose options, but decisions like separating RAG from FAQ cache or using Notion as CMS with PostgreSQL as the retrieval cache were judgments I had to own.',
      '',
      '> AI lends me execution speed. But direction, sensibility, and review are still human work. That is what I am actively training.',
      '',
      'So I think the more realistic question is not "will AI replace developers?" It is "will developers who use AI well replace those who do not?"',
    ].join('\n'),
    detailedAnswer: [
      'I would not frame this as mysterious human superiority. A more accurate framing is that AI is powerful, but disconnected from many real-world contexts.',
      '',
      'An LLM is like someone isolated on an island surrounded by enormous stacks of books. It has a lot of knowledge and speed, but it does not directly know what a real user finds frustrating, what this team needs this week, or which UI copy will lose trust.',
      '',
      'Running OOSU SALON trained me to read user reactions in real time. Working at GfK trained me to read context behind data. That is the standard I now use when reviewing and refining AI output.',
      '',
      'So Oosu is not trying to compete with AI. The goal is to connect AI to real users, product context, and responsible judgment.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.replace_developer.default',
      'ops.ai-agent-workflow.en',
      'ops.product-build-loop.en',
      'ops.code-review-with-ai.en',
      'decision.why-not-overclaim-ai-era.en',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsEn,
    matchedEntityIds: [
      'ai_era_competitiveness',
      'ai_usage',
      'profile',
      'askoosu',
    ],
    confidence: 0.92,
  }),
  createAiEraAnswer({
    id: 'faq.ai_era.skill_atrophy.default',
    intentId: 'ai_era.skill_atrophy',
    entityId: 'ai_era_competitiveness',
    language: 'en',
    quickLabel: 'AI and skill',
    displayQuestion:
      "Doesn't using AI tools a lot mean you're not actually developing your skills?",
    alternativeDisplayQuestions: [
      'Can you actually understand and write code yourself?',
      'Can you code without AI?',
    ],
    patterns: [
      'AI dependency skill atrophy',
      'real skills',
      'can you code without AI',
      'AI fluency vs skill',
      'using AI too much',
      'does Oosu actually code',
    ],
    shortAnswer:
      'Using AI well is different from depending on AI. Oosu tries to understand the design and flow first, then borrow AI speed while reviewing the result.',
    defaultAnswer: [
      'Early on, I experienced the exact risk: AI-generated code could run, but when I did not understand why it ran, I could not fix it when things broke. That frustration shaped my current workflow.',
      '',
      'Now I define the goal, edit scope, constraints, and test criteria before delegating to AI. Then I check whether the result references the real file structure, whether API and UI fields match, and whether any secrets or sensitive data are exposed.',
      '',
      '> To use AI well, you have to be capable of reviewing it well.',
      '',
      'That review requires me to actually know what is happening. So AI is not a replacement for understanding; it is an amplifier for learning and execution speed.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.skill_atrophy.default',
      'ops.code-review-with-ai.en',
      'postmortem.instagram-clone-fullstack-lessons.en',
      'decision.why-not-overclaim-ai-era.en',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsEn,
    matchedEntityIds: ['ai_era_competitiveness', 'ai_usage', 'profile'],
    confidence: 0.91,
  }),
  createAiEraAnswer({
    id: 'faq.ai_era.competitiveness_source.default',
    legacyIds: ['faq.ai_competitiveness.real_competitor.default'],
    intentId: 'ai_era.competitiveness_source',
    entityId: 'ai_era_competitiveness',
    language: 'en',
    quickLabel: 'Competitive edge',
    displayQuestion:
      "Where does Oosu's competitive edge come from in the AI era?",
    alternativeDisplayQuestions: [
      'Who do you think your competitors are?',
      'Why hire Oosu in the AI era?',
    ],
    patterns: [
      'competitive advantage',
      'strengths',
      'AI era differentiation',
      'why hire Oosu',
      'what makes Oosu different',
      'AI is your competitor',
      'competing with AI',
      'who are your competitors',
    ],
    shortAnswer:
      "Oosu's edge is not competing with AI itself. It is the speed and review habit of connecting AI to real user problems and product judgment.",
    defaultAnswer: [
      'I think it comes from three things.',
      '',
      '**One: connected experience.** Customer research, data analytics, running OOSU SALON, UX/UI, Fullstack, and AI/RAG are not separate chapters. Each stage became a standard for the next.',
      '',
      '**Two: the instinct to connect AI to reality.** AI suggests possibilities, but judging whether those possibilities fit this user, this team, and this product comes from lived experience.',
      '',
      '**Three: speed of experimentation.** Groq, pgvector, Cloudflare Tunnel, and Vercel AI SDK were not just things I read about. I used them while building AskOosu and connected them to production.',
      '',
      '> AI itself is not my competitor. Developers who use AI effectively are my competitors. I am preparing to be on that side.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.competitiveness_source.default',
      'decision.why-ai-native-working-thesis.en',
      'project.askoosu.fact',
      'profile.learning_style',
      'career.timeline',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsEn,
    matchedEntityIds: [
      'ai_era_competitiveness',
      'profile',
      'career',
      'askoosu',
    ],
    confidence: 0.92,
  }),
  createAiEraAnswer({
    id: 'faq.ai_competitiveness.ai_fluency_vs_dependency.default',
    intentId: 'ai_competitiveness.ai_fluency_vs_dependency',
    entityId: 'ai_era_competitiveness',
    language: 'en',
    quickLabel: 'AI fluency',
    displayQuestion:
      "What's the difference between using AI well and being dependent on AI?",
    patterns: [
      'AI dependency',
      'using AI well',
      "can't code without AI",
      'AI fluency',
      'AI fluency vs dependency',
    ],
    shortAnswer:
      'AI dependency means accepting results without understanding them. AI fluency means defining goals and validation criteria, then taking responsibility for integration.',
    defaultAnswer: [
      'Being dependent on AI means accepting results without understanding them. Using AI well means defining the goal, scope, and validation criteria first, then taking responsibility for integrating the result.',
      '',
      'Oosu tries to define the objective, modification scope, things to avoid, and test criteria before handing work to AI. Then the result is reviewed inside the actual codebase and product flow.',
      '',
      '> AI code is a draft; the judgment that goes into the product is still mine.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_competitiveness.ai_fluency_vs_dependency.default',
      'ops.ai-agent-workflow.en',
      'ops.code-review-with-ai.en',
      'ops.answer-quality-loop.en',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsEn,
    matchedEntityIds: ['ai_era_competitiveness', 'ai_usage', 'askoosu'],
    confidence: 0.91,
  }),
];

function createAiEraAnswer(input: AiEraFaqInput): FaqAnswer {
  return {
    ...input,
    answer: input.defaultAnswer,
    cacheMode: 'direct_cache',
    answerSource: 'faq_cache',
    skippedGroq: true,
    visibility: input.visibility ?? 'public',
  };
}
